// Code generated by protoc-gen-go. DO NOT EDIT.
// source: istio/v1/messages.proto

package istio

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyKind int32

const (
	KeyKind_UNKNOWN KeyKind = 0
	KeyKind_AES     KeyKind = 1
	KeyKind_RSA     KeyKind = 2
	KeyKind_ECC     KeyKind = 3
)

var KeyKind_name = map[int32]string{
	0: "UNKNOWN",
	1: "AES",
	2: "RSA",
	3: "ECC",
}

var KeyKind_value = map[string]int32{
	"UNKNOWN": 0,
	"AES":     1,
	"RSA":     2,
	"ECC":     3,
}

func (x KeyKind) String() string {
	return proto.EnumName(KeyKind_name, int32(x))
}

func (KeyKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{0}
}

type Curve int32

const (
	Curve_UNSUPPORTED Curve = 0
	Curve_ED25519     Curve = 1
)

var Curve_name = map[int32]string{
	0: "UNSUPPORTED",
	1: "ED25519",
}

var Curve_value = map[string]int32{
	"UNSUPPORTED": 0,
	"ED25519":     1,
}

func (x Curve) String() string {
	return proto.EnumName(Curve_name, int32(x))
}

func (Curve) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{1}
}

type GenerateKEKRequest struct {
	// optional kid, otherwise will be autogenerated as a UUID.v4 in the response
	KekKid               []byte   `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKEKRequest) Reset()         { *m = GenerateKEKRequest{} }
func (m *GenerateKEKRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKEKRequest) ProtoMessage()    {}
func (*GenerateKEKRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{0}
}

func (m *GenerateKEKRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKEKRequest.Unmarshal(m, b)
}
func (m *GenerateKEKRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKEKRequest.Marshal(b, m, deterministic)
}
func (m *GenerateKEKRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKEKRequest.Merge(m, src)
}
func (m *GenerateKEKRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKEKRequest.Size(m)
}
func (m *GenerateKEKRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKEKRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKEKRequest proto.InternalMessageInfo

func (m *GenerateKEKRequest) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

type GenerateKEKResponse struct {
	// KEK kid
	KekKid               []byte   `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKEKResponse) Reset()         { *m = GenerateKEKResponse{} }
func (m *GenerateKEKResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateKEKResponse) ProtoMessage()    {}
func (*GenerateKEKResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{1}
}

func (m *GenerateKEKResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKEKResponse.Unmarshal(m, b)
}
func (m *GenerateKEKResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKEKResponse.Marshal(b, m, deterministic)
}
func (m *GenerateKEKResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKEKResponse.Merge(m, src)
}
func (m *GenerateKEKResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateKEKResponse.Size(m)
}
func (m *GenerateKEKResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKEKResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKEKResponse proto.InternalMessageInfo

func (m *GenerateKEKResponse) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

type GenerateDEKRequest struct {
	// Wrapping/Encrypting KEK ID
	KekKid               []byte   `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateDEKRequest) Reset()         { *m = GenerateDEKRequest{} }
func (m *GenerateDEKRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateDEKRequest) ProtoMessage()    {}
func (*GenerateDEKRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{2}
}

func (m *GenerateDEKRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateDEKRequest.Unmarshal(m, b)
}
func (m *GenerateDEKRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateDEKRequest.Marshal(b, m, deterministic)
}
func (m *GenerateDEKRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateDEKRequest.Merge(m, src)
}
func (m *GenerateDEKRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateDEKRequest.Size(m)
}
func (m *GenerateDEKRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateDEKRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateDEKRequest proto.InternalMessageInfo

func (m *GenerateDEKRequest) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

type GenerateDEKResponse struct {
	// Encrypted key blob
	EncryptedDekBlob     []byte   `protobuf:"bytes,1,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateDEKResponse) Reset()         { *m = GenerateDEKResponse{} }
func (m *GenerateDEKResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateDEKResponse) ProtoMessage()    {}
func (*GenerateDEKResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{3}
}

func (m *GenerateDEKResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateDEKResponse.Unmarshal(m, b)
}
func (m *GenerateDEKResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateDEKResponse.Marshal(b, m, deterministic)
}
func (m *GenerateDEKResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateDEKResponse.Merge(m, src)
}
func (m *GenerateDEKResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateDEKResponse.Size(m)
}
func (m *GenerateDEKResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateDEKResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateDEKResponse proto.InternalMessageInfo

func (m *GenerateDEKResponse) GetEncryptedDekBlob() []byte {
	if m != nil {
		return m.EncryptedDekBlob
	}
	return nil
}

type GenerateSKeyRequest struct {
	// key size in bits
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// What kind of key is it... only Asymmetric kinds will be supported
	Kind KeyKind `protobuf:"varint,2,opt,name=kind,proto3,enum=thales.cpl.kms.istio.v1.KeyKind" json:"kind,omitempty"`
	// Curves
	Curve Curve `protobuf:"varint,3,opt,name=curve,proto3,enum=thales.cpl.kms.istio.v1.Curve" json:"curve,omitempty"`
	// Parent KID of the KEK
	KekKid []byte `protobuf:"bytes,4,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	// Encrypted blob of DEK
	EncryptedDekBlob     []byte   `protobuf:"bytes,5,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSKeyRequest) Reset()         { *m = GenerateSKeyRequest{} }
func (m *GenerateSKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSKeyRequest) ProtoMessage()    {}
func (*GenerateSKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{4}
}

func (m *GenerateSKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSKeyRequest.Unmarshal(m, b)
}
func (m *GenerateSKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateSKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSKeyRequest.Merge(m, src)
}
func (m *GenerateSKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateSKeyRequest.Size(m)
}
func (m *GenerateSKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSKeyRequest proto.InternalMessageInfo

func (m *GenerateSKeyRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GenerateSKeyRequest) GetKind() KeyKind {
	if m != nil {
		return m.Kind
	}
	return KeyKind_UNKNOWN
}

func (m *GenerateSKeyRequest) GetCurve() Curve {
	if m != nil {
		return m.Curve
	}
	return Curve_UNSUPPORTED
}

func (m *GenerateSKeyRequest) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

func (m *GenerateSKeyRequest) GetEncryptedDekBlob() []byte {
	if m != nil {
		return m.EncryptedDekBlob
	}
	return nil
}

type GenerateSKeyResponse struct {
	// Encrypted blob of SKey encrypted by DEK
	EncryptedSkeyBlob    []byte   `protobuf:"bytes,1,opt,name=encrypted_skey_blob,json=encryptedSkeyBlob,proto3" json:"encrypted_skey_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSKeyResponse) Reset()         { *m = GenerateSKeyResponse{} }
func (m *GenerateSKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateSKeyResponse) ProtoMessage()    {}
func (*GenerateSKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{5}
}

func (m *GenerateSKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSKeyResponse.Unmarshal(m, b)
}
func (m *GenerateSKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSKeyResponse.Marshal(b, m, deterministic)
}
func (m *GenerateSKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSKeyResponse.Merge(m, src)
}
func (m *GenerateSKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateSKeyResponse.Size(m)
}
func (m *GenerateSKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSKeyResponse proto.InternalMessageInfo

func (m *GenerateSKeyResponse) GetEncryptedSkeyBlob() []byte {
	if m != nil {
		return m.EncryptedSkeyBlob
	}
	return nil
}

type LoadSKeyRequest struct {
	// KEK
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	// Encrypted blob of DEK
	EncryptedDekBlob []byte `protobuf:"bytes,2,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	// Encrypted blob of SKey
	EncryptedSkeyBlob    []byte   `protobuf:"bytes,3,opt,name=encrypted_skey_blob,json=encryptedSkeyBlob,proto3" json:"encrypted_skey_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadSKeyRequest) Reset()         { *m = LoadSKeyRequest{} }
func (m *LoadSKeyRequest) String() string { return proto.CompactTextString(m) }
func (*LoadSKeyRequest) ProtoMessage()    {}
func (*LoadSKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{6}
}

func (m *LoadSKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadSKeyRequest.Unmarshal(m, b)
}
func (m *LoadSKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadSKeyRequest.Marshal(b, m, deterministic)
}
func (m *LoadSKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadSKeyRequest.Merge(m, src)
}
func (m *LoadSKeyRequest) XXX_Size() int {
	return xxx_messageInfo_LoadSKeyRequest.Size(m)
}
func (m *LoadSKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadSKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadSKeyRequest proto.InternalMessageInfo

func (m *LoadSKeyRequest) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

func (m *LoadSKeyRequest) GetEncryptedDekBlob() []byte {
	if m != nil {
		return m.EncryptedDekBlob
	}
	return nil
}

func (m *LoadSKeyRequest) GetEncryptedSkeyBlob() []byte {
	if m != nil {
		return m.EncryptedSkeyBlob
	}
	return nil
}

type LoadSKeyResponse struct {
	// Intermediate CA Signing KeyPair in plaintext in PEM Format
	PlaintextSkey        []byte   `protobuf:"bytes,1,opt,name=plaintext_skey,json=plaintextSkey,proto3" json:"plaintext_skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadSKeyResponse) Reset()         { *m = LoadSKeyResponse{} }
func (m *LoadSKeyResponse) String() string { return proto.CompactTextString(m) }
func (*LoadSKeyResponse) ProtoMessage()    {}
func (*LoadSKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{7}
}

func (m *LoadSKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadSKeyResponse.Unmarshal(m, b)
}
func (m *LoadSKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadSKeyResponse.Marshal(b, m, deterministic)
}
func (m *LoadSKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadSKeyResponse.Merge(m, src)
}
func (m *LoadSKeyResponse) XXX_Size() int {
	return xxx_messageInfo_LoadSKeyResponse.Size(m)
}
func (m *LoadSKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadSKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadSKeyResponse proto.InternalMessageInfo

func (m *LoadSKeyResponse) GetPlaintextSkey() []byte {
	if m != nil {
		return m.PlaintextSkey
	}
	return nil
}

// AuthenticatedEncryptRequest
type AuthenticatedEncryptRequest struct {
	KekKid               []byte   `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	EncryptedDekBlob     []byte   `protobuf:"bytes,2,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	Plaintext            []byte   `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Aad                  []byte   `protobuf:"bytes,4,opt,name=aad,proto3" json:"aad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticatedEncryptRequest) Reset()         { *m = AuthenticatedEncryptRequest{} }
func (m *AuthenticatedEncryptRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedEncryptRequest) ProtoMessage()    {}
func (*AuthenticatedEncryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{8}
}

func (m *AuthenticatedEncryptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedEncryptRequest.Unmarshal(m, b)
}
func (m *AuthenticatedEncryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedEncryptRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticatedEncryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedEncryptRequest.Merge(m, src)
}
func (m *AuthenticatedEncryptRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedEncryptRequest.Size(m)
}
func (m *AuthenticatedEncryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedEncryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedEncryptRequest proto.InternalMessageInfo

func (m *AuthenticatedEncryptRequest) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

func (m *AuthenticatedEncryptRequest) GetEncryptedDekBlob() []byte {
	if m != nil {
		return m.EncryptedDekBlob
	}
	return nil
}

func (m *AuthenticatedEncryptRequest) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

func (m *AuthenticatedEncryptRequest) GetAad() []byte {
	if m != nil {
		return m.Aad
	}
	return nil
}

// AuthenticatedEncryptResponse
type AuthenticatedEncryptResponse struct {
	Ciphertext           []byte   `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticatedEncryptResponse) Reset()         { *m = AuthenticatedEncryptResponse{} }
func (m *AuthenticatedEncryptResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedEncryptResponse) ProtoMessage()    {}
func (*AuthenticatedEncryptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{9}
}

func (m *AuthenticatedEncryptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedEncryptResponse.Unmarshal(m, b)
}
func (m *AuthenticatedEncryptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedEncryptResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticatedEncryptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedEncryptResponse.Merge(m, src)
}
func (m *AuthenticatedEncryptResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedEncryptResponse.Size(m)
}
func (m *AuthenticatedEncryptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedEncryptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedEncryptResponse proto.InternalMessageInfo

func (m *AuthenticatedEncryptResponse) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

// AuthenticatedDecryptRequest
type AuthenticatedDecryptRequest struct {
	KekKid               []byte   `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	EncryptedDekBlob     []byte   `protobuf:"bytes,2,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Aad                  []byte   `protobuf:"bytes,4,opt,name=aad,proto3" json:"aad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticatedDecryptRequest) Reset()         { *m = AuthenticatedDecryptRequest{} }
func (m *AuthenticatedDecryptRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedDecryptRequest) ProtoMessage()    {}
func (*AuthenticatedDecryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{10}
}

func (m *AuthenticatedDecryptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedDecryptRequest.Unmarshal(m, b)
}
func (m *AuthenticatedDecryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedDecryptRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticatedDecryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedDecryptRequest.Merge(m, src)
}
func (m *AuthenticatedDecryptRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedDecryptRequest.Size(m)
}
func (m *AuthenticatedDecryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedDecryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedDecryptRequest proto.InternalMessageInfo

func (m *AuthenticatedDecryptRequest) GetKekKid() []byte {
	if m != nil {
		return m.KekKid
	}
	return nil
}

func (m *AuthenticatedDecryptRequest) GetEncryptedDekBlob() []byte {
	if m != nil {
		return m.EncryptedDekBlob
	}
	return nil
}

func (m *AuthenticatedDecryptRequest) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *AuthenticatedDecryptRequest) GetAad() []byte {
	if m != nil {
		return m.Aad
	}
	return nil
}

// AuthenticatedDecryptResponse
type AuthenticatedDecryptResponse struct {
	Plaintext            []byte   `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticatedDecryptResponse) Reset()         { *m = AuthenticatedDecryptResponse{} }
func (m *AuthenticatedDecryptResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedDecryptResponse) ProtoMessage()    {}
func (*AuthenticatedDecryptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{11}
}

func (m *AuthenticatedDecryptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedDecryptResponse.Unmarshal(m, b)
}
func (m *AuthenticatedDecryptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedDecryptResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticatedDecryptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedDecryptResponse.Merge(m, src)
}
func (m *AuthenticatedDecryptResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedDecryptResponse.Size(m)
}
func (m *AuthenticatedDecryptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedDecryptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedDecryptResponse proto.InternalMessageInfo

func (m *AuthenticatedDecryptResponse) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

// ImportCACertRequest
type ImportCACertRequest struct {
	CaId                 []byte   `protobuf:"bytes,1,opt,name=ca_id,json=caId,proto3" json:"ca_id,omitempty"`
	CaCertBlob           []byte   `protobuf:"bytes,2,opt,name=ca_cert_blob,json=caCertBlob,proto3" json:"ca_cert_blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportCACertRequest) Reset()         { *m = ImportCACertRequest{} }
func (m *ImportCACertRequest) String() string { return proto.CompactTextString(m) }
func (*ImportCACertRequest) ProtoMessage()    {}
func (*ImportCACertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{12}
}

func (m *ImportCACertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportCACertRequest.Unmarshal(m, b)
}
func (m *ImportCACertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportCACertRequest.Marshal(b, m, deterministic)
}
func (m *ImportCACertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportCACertRequest.Merge(m, src)
}
func (m *ImportCACertRequest) XXX_Size() int {
	return xxx_messageInfo_ImportCACertRequest.Size(m)
}
func (m *ImportCACertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportCACertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportCACertRequest proto.InternalMessageInfo

func (m *ImportCACertRequest) GetCaId() []byte {
	if m != nil {
		return m.CaId
	}
	return nil
}

func (m *ImportCACertRequest) GetCaCertBlob() []byte {
	if m != nil {
		return m.CaCertBlob
	}
	return nil
}

// ImportCACertResponse
type ImportCACertResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportCACertResponse) Reset()         { *m = ImportCACertResponse{} }
func (m *ImportCACertResponse) String() string { return proto.CompactTextString(m) }
func (*ImportCACertResponse) ProtoMessage()    {}
func (*ImportCACertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{13}
}

func (m *ImportCACertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportCACertResponse.Unmarshal(m, b)
}
func (m *ImportCACertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportCACertResponse.Marshal(b, m, deterministic)
}
func (m *ImportCACertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportCACertResponse.Merge(m, src)
}
func (m *ImportCACertResponse) XXX_Size() int {
	return xxx_messageInfo_ImportCACertResponse.Size(m)
}
func (m *ImportCACertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportCACertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportCACertResponse proto.InternalMessageInfo

func (m *ImportCACertResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// VerifyCertChainRequest
type VerifyCertChainRequest struct {
	Certificates         [][]byte `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyCertChainRequest) Reset()         { *m = VerifyCertChainRequest{} }
func (m *VerifyCertChainRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyCertChainRequest) ProtoMessage()    {}
func (*VerifyCertChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{14}
}

func (m *VerifyCertChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCertChainRequest.Unmarshal(m, b)
}
func (m *VerifyCertChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCertChainRequest.Marshal(b, m, deterministic)
}
func (m *VerifyCertChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCertChainRequest.Merge(m, src)
}
func (m *VerifyCertChainRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyCertChainRequest.Size(m)
}
func (m *VerifyCertChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCertChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCertChainRequest proto.InternalMessageInfo

func (m *VerifyCertChainRequest) GetCertificates() [][]byte {
	if m != nil {
		return m.Certificates
	}
	return nil
}

// VerifyCertChainResponse
type VerifyCertChainResponse struct {
	SuccessfulVerification bool     `protobuf:"varint,1,opt,name=successful_verification,json=successfulVerification,proto3" json:"successful_verification,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *VerifyCertChainResponse) Reset()         { *m = VerifyCertChainResponse{} }
func (m *VerifyCertChainResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyCertChainResponse) ProtoMessage()    {}
func (*VerifyCertChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438549198496a229, []int{15}
}

func (m *VerifyCertChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCertChainResponse.Unmarshal(m, b)
}
func (m *VerifyCertChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCertChainResponse.Marshal(b, m, deterministic)
}
func (m *VerifyCertChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCertChainResponse.Merge(m, src)
}
func (m *VerifyCertChainResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyCertChainResponse.Size(m)
}
func (m *VerifyCertChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCertChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCertChainResponse proto.InternalMessageInfo

func (m *VerifyCertChainResponse) GetSuccessfulVerification() bool {
	if m != nil {
		return m.SuccessfulVerification
	}
	return false
}

func init() {
	proto.RegisterEnum("thales.cpl.kms.istio.v1.KeyKind", KeyKind_name, KeyKind_value)
	proto.RegisterEnum("thales.cpl.kms.istio.v1.Curve", Curve_name, Curve_value)
	proto.RegisterType((*GenerateKEKRequest)(nil), "thales.cpl.kms.istio.v1.GenerateKEKRequest")
	proto.RegisterType((*GenerateKEKResponse)(nil), "thales.cpl.kms.istio.v1.GenerateKEKResponse")
	proto.RegisterType((*GenerateDEKRequest)(nil), "thales.cpl.kms.istio.v1.GenerateDEKRequest")
	proto.RegisterType((*GenerateDEKResponse)(nil), "thales.cpl.kms.istio.v1.GenerateDEKResponse")
	proto.RegisterType((*GenerateSKeyRequest)(nil), "thales.cpl.kms.istio.v1.GenerateSKeyRequest")
	proto.RegisterType((*GenerateSKeyResponse)(nil), "thales.cpl.kms.istio.v1.GenerateSKeyResponse")
	proto.RegisterType((*LoadSKeyRequest)(nil), "thales.cpl.kms.istio.v1.LoadSKeyRequest")
	proto.RegisterType((*LoadSKeyResponse)(nil), "thales.cpl.kms.istio.v1.LoadSKeyResponse")
	proto.RegisterType((*AuthenticatedEncryptRequest)(nil), "thales.cpl.kms.istio.v1.AuthenticatedEncryptRequest")
	proto.RegisterType((*AuthenticatedEncryptResponse)(nil), "thales.cpl.kms.istio.v1.AuthenticatedEncryptResponse")
	proto.RegisterType((*AuthenticatedDecryptRequest)(nil), "thales.cpl.kms.istio.v1.AuthenticatedDecryptRequest")
	proto.RegisterType((*AuthenticatedDecryptResponse)(nil), "thales.cpl.kms.istio.v1.AuthenticatedDecryptResponse")
	proto.RegisterType((*ImportCACertRequest)(nil), "thales.cpl.kms.istio.v1.ImportCACertRequest")
	proto.RegisterType((*ImportCACertResponse)(nil), "thales.cpl.kms.istio.v1.ImportCACertResponse")
	proto.RegisterType((*VerifyCertChainRequest)(nil), "thales.cpl.kms.istio.v1.VerifyCertChainRequest")
	proto.RegisterType((*VerifyCertChainResponse)(nil), "thales.cpl.kms.istio.v1.VerifyCertChainResponse")
}

func init() { proto.RegisterFile("istio/v1/messages.proto", fileDescriptor_438549198496a229) }

var fileDescriptor_438549198496a229 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xd1, 0x6e, 0xe2, 0x46,
	0x14, 0x5d, 0xc7, 0xb0, 0xb4, 0x77, 0xe9, 0xae, 0x6b, 0x56, 0x0b, 0xda, 0x46, 0x29, 0xb2, 0x14,
	0x29, 0x8a, 0x82, 0x5d, 0xd2, 0x44, 0x6d, 0xda, 0xa8, 0x12, 0x01, 0x5a, 0x45, 0x44, 0x24, 0x32,
	0x4d, 0x2a, 0xf5, 0x05, 0x0d, 0xf6, 0xc5, 0x8c, 0x6c, 0x3c, 0xae, 0x67, 0x4c, 0x4b, 0xbf, 0xa0,
	0x1f, 0x50, 0xf5, 0xeb, 0xfa, 0x31, 0x95, 0x07, 0x03, 0x86, 0xc6, 0x52, 0x1f, 0xba, 0x4f, 0x5c,
	0xe6, 0x9e, 0x73, 0xee, 0x39, 0xd7, 0xd6, 0x18, 0xea, 0x94, 0x0b, 0xca, 0xac, 0x45, 0xdb, 0x9a,
	0x23, 0xe7, 0xc4, 0x43, 0x6e, 0x46, 0x31, 0x13, 0x4c, 0xaf, 0x8b, 0x19, 0x09, 0x90, 0x9b, 0x4e,
	0x14, 0x98, 0xfe, 0x9c, 0x9b, 0x12, 0x67, 0x2e, 0xda, 0xef, 0x3f, 0xf7, 0x18, 0xf3, 0x02, 0xb4,
	0x24, 0x6c, 0x92, 0x4c, 0x2d, 0x41, 0xe7, 0xc8, 0x05, 0x99, 0x47, 0x2b, 0xe6, 0xfb, 0x33, 0xf9,
	0xe3, 0xb4, 0x3c, 0x0c, 0x5b, 0xfc, 0x57, 0xe2, 0x79, 0x18, 0x5b, 0x2c, 0x12, 0x94, 0x85, 0xdc,
	0x22, 0x61, 0xc8, 0x04, 0x91, 0xf5, 0x0a, 0x6d, 0xb4, 0x40, 0xff, 0x01, 0x43, 0x8c, 0x89, 0xc0,
	0x41, 0x7f, 0x60, 0xe3, 0x2f, 0x09, 0x72, 0xa1, 0xd7, 0xa1, 0xe2, 0xa3, 0x3f, 0xf6, 0xa9, 0xdb,
	0x50, 0x9a, 0xca, 0x49, 0xd5, 0x7e, 0xe9, 0xa3, 0x3f, 0xa0, 0xae, 0x61, 0x42, 0x6d, 0x07, 0xce,
	0x23, 0x16, 0x72, 0x2c, 0xc6, 0xe7, 0xe4, 0x7b, 0xff, 0x41, 0xbe, 0xbb, 0x95, 0xef, 0xe5, 0xe4,
	0xcf, 0x40, 0xc7, 0xd0, 0x89, 0x97, 0x91, 0x40, 0x77, 0xec, 0xa2, 0x3f, 0x9e, 0x04, 0x6c, 0x92,
	0x51, 0xb5, 0x4d, 0xa7, 0x87, 0xfe, 0x4d, 0xc0, 0x26, 0xc6, 0xdf, 0xca, 0x56, 0x65, 0x34, 0xc0,
	0xe5, 0x7a, 0xaa, 0x0e, 0x25, 0x4e, 0x7f, 0x47, 0xc9, 0x53, 0x6d, 0x59, 0xeb, 0x17, 0x50, 0xf2,
	0x69, 0xe8, 0x36, 0x0e, 0x9a, 0xca, 0xc9, 0xeb, 0xf3, 0xa6, 0x59, 0xb0, 0x75, 0x73, 0x80, 0xcb,
	0x01, 0x0d, 0x5d, 0x5b, 0xa2, 0xf5, 0x0b, 0x28, 0x3b, 0x49, 0xbc, 0xc0, 0x86, 0x2a, 0x69, 0x47,
	0x85, 0xb4, 0x6e, 0x8a, 0xb2, 0x57, 0xe0, 0x7c, 0xea, 0x52, 0x3e, 0x75, 0x41, 0xbc, 0x72, 0x41,
	0xbc, 0xef, 0xe1, 0xed, 0x6e, 0xba, 0x6c, 0x49, 0x26, 0xd4, 0xb6, 0x2a, 0xdc, 0xc7, 0x65, 0x7e,
	0x4b, 0x9f, 0x6e, 0x5a, 0x23, 0x1f, 0x97, 0x52, 0xe7, 0x0f, 0x05, 0xde, 0xdc, 0x31, 0xe2, 0xe6,
	0x57, 0x54, 0xf4, 0x60, 0x0a, 0x2c, 0x1e, 0x3c, 0x6f, 0xb1, 0xc8, 0x8a, 0x5a, 0x64, 0xe5, 0x0a,
	0xb4, 0xad, 0x93, 0x2c, 0xce, 0x31, 0xbc, 0x8e, 0x02, 0x42, 0x43, 0x81, 0xbf, 0x09, 0xa9, 0x91,
	0x39, 0xfa, 0x64, 0x73, 0x9a, 0xd2, 0x8d, 0x3f, 0x15, 0xf8, 0xac, 0x93, 0x88, 0x19, 0x86, 0x82,
	0x3a, 0x44, 0xa0, 0xdb, 0x5f, 0xa9, 0xff, 0xcf, 0x89, 0x0e, 0xe1, 0xe3, 0xcd, 0xdc, 0x2c, 0xc7,
	0xf6, 0x40, 0xd7, 0x40, 0x25, 0x64, 0xfd, 0x54, 0xd3, 0xd2, 0xf8, 0x0e, 0x0e, 0x9f, 0x77, 0x95,
	0xa5, 0x3b, 0x02, 0x70, 0x68, 0x34, 0xc3, 0x58, 0x0a, 0xae, 0x9c, 0xe5, 0x4e, 0x8c, 0xbf, 0xf6,
	0x63, 0xf5, 0xf0, 0x43, 0xc4, 0xda, 0xb5, 0xa1, 0xee, 0xdb, 0x78, 0x26, 0xd8, 0xf5, 0x5e, 0xb0,
	0x8d, 0xaf, 0x2c, 0xd8, 0xce, 0xa2, 0x94, 0xbd, 0x45, 0x19, 0x77, 0x50, 0xbb, 0x9d, 0x47, 0x2c,
	0x16, 0xdd, 0x4e, 0x17, 0xe3, 0x4d, 0x9a, 0x1a, 0x94, 0x1d, 0x32, 0xde, 0x64, 0x29, 0x39, 0xe4,
	0xd6, 0xd5, 0x9b, 0x50, 0x75, 0xc8, 0xd8, 0xc1, 0x58, 0xe4, 0x33, 0x80, 0x43, 0x52, 0xa6, 0x7c,
	0x6d, 0xbe, 0x80, 0xb7, 0xbb, 0x6a, 0x99, 0x87, 0x06, 0x54, 0x78, 0xe2, 0x38, 0xc8, 0xb9, 0x14,
	0xfc, 0xc8, 0x5e, 0xff, 0x35, 0xae, 0xe1, 0xdd, 0x13, 0xc6, 0x74, 0xba, 0x4c, 0xf1, 0xdd, 0x19,
	0xa1, 0xe1, 0xda, 0x82, 0x01, 0xd5, 0x74, 0x14, 0x9d, 0xca, 0x58, 0x29, 0x51, 0x3d, 0xa9, 0xda,
	0x3b, 0x67, 0x86, 0x0d, 0xf5, 0x7f, 0xb1, 0xb3, 0x91, 0x5f, 0x41, 0x3d, 0x9b, 0x31, 0x4d, 0x82,
	0xf1, 0x22, 0x45, 0xa5, 0x24, 0xca, 0xc2, 0xcc, 0xc2, 0xbb, 0x6d, 0xfb, 0x29, 0xd7, 0x3d, 0x6d,
	0x43, 0x25, 0xbb, 0x5b, 0xf4, 0x57, 0x50, 0x79, 0x1c, 0x0e, 0x86, 0xf7, 0x3f, 0x0d, 0xb5, 0x17,
	0x7a, 0x05, 0xd4, 0x4e, 0x7f, 0xa4, 0x29, 0x69, 0x61, 0x8f, 0x3a, 0xda, 0x41, 0x5a, 0xf4, 0xbb,
	0x5d, 0x4d, 0x3d, 0x3d, 0x86, 0xb2, 0xbc, 0x57, 0xf4, 0x37, 0xf0, 0xea, 0x71, 0x38, 0x7a, 0x7c,
	0x78, 0xb8, 0xb7, 0x7f, 0xec, 0xf7, 0xb4, 0x17, 0xa9, 0x42, 0xbf, 0x77, 0x7e, 0x79, 0xd9, 0xbe,
	0xd2, 0x94, 0x9b, 0xeb, 0x9f, 0xbf, 0xf1, 0xa8, 0x98, 0x25, 0x13, 0xd3, 0x61, 0x73, 0x6b, 0x75,
	0x43, 0x39, 0x51, 0xd0, 0xa2, 0xcc, 0xf2, 0xbf, 0xe6, 0x2d, 0x7f, 0xce, 0x5b, 0x51, 0x90, 0x78,
	0x34, 0x6c, 0x91, 0x88, 0x72, 0x6b, 0xfd, 0x21, 0xfa, 0x56, 0x16, 0x93, 0x97, 0xf2, 0xf3, 0xf0,
	0xe5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0xec, 0x11, 0xc7, 0xa1, 0x06, 0x00, 0x00,
}
